version: "2"

services:
  web:
    build: web
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=jpe-db.postgres.database.azure.com"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=nmikuni@jpe-db"
      - "DATABASE_PASSWORD=N@mick39"
    volumes:
      - "./app:/app" #共有フォルダの設定
    stdin_open: true
